DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" varchar,
  "department" integer,
  "employmentType" integer,
  "position" integer,
  "leave" integer,
  "training" integer,
  "attendance" integer,
  "created_at" timestamp
);

INSERT INTO users
(fullName, department, employmentType, position, leave, training, attendance) 
VALUES
('John Doe', 'HR', 'Full-Time', 'HR Manager', 10, 'Onboarding', 'Present'),
('Jane Smith', 'Marketing', 'Part-Time', 'Marketing Coordinator', 5, 'Marketing Strategy', 'Present'),
('Mike Johnson', 'IT', 'Full-Time', 'Systems Administrator', 12, 'Cybersecurity', 'Absent'),
('Sarah Brown', 'Finance', 'Full-Time', 'Financial Analyst', 8, 'Financial Planning', 'Present'),
('David Lee', 'Sales', 'Part-Time', 'Sales Associate', 7, 'Sales Techniques', 'Present');

DROP TABLE IF EXISTS departments CASCADE;
CREATE TABLE "departments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departmentId" int,
  "title" varchar,
  "description" varchar,
  "created_at" timestamp
);

INSERT INTO departments
("id", "title", "description", "created_at")
VALUES
(1, 'HR', 'Human Resources Department', '2023-09-12 10:00:00'),
(2, 'Marketing', 'Marketing Department', '2023-09-12 10:15:00'),
(3, 'IT', 'Information Technology Department', '2023-09-12 10:30:00'),
(4, 'Finance', 'Finance Department', '2023-09-12 10:45:00'),
(5, 'Sales', 'Sales Department', '2023-09-12 11:00:00');

DROP TABLE IF EXISTS positions CASCADE;
CREATE TABLE "positions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postId" int,
  "department" integer,
  "position" varchar,
  "created_at" timestamp
);

INSERT INTO positions
("id", "department", "position", "created_at")
VALUES
(1, 1, 'HR Manager', '2023-09-12 13:00:00'),
(2, 2, 'Marketing Coordinator', '2023-09-12 13:15:00'),
(3, 3, 'Systems Administrator', '2023-09-12 13:30:00'),
(4, 4, 'Financial Analyst', '2023-09-12 13:45:00'),
(5, 5, 'Sales Associate', '2023-09-12 14:00:00');

DROP TABLE IF EXISTS employmentTypes CASCADE;

CREATE TABLE "employmentType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypeId" int,
  "employment" varchar,
  "created_at" timestamp
);

INSERT INTO employmentTypes
("id", "type", "created_at")
VALUES
(1, 'Full-Time', '2023-09-12 15:00:00'),
(2, 'Part-Time', '2023-09-12 15:15:00'),
(3, 'Contract', '2023-09-12 15:30:00'),
(4, 'Temporary', '2023-09-12 15:45:00');



CREATE TABLE "partTime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ParttimeID" int,
  "hourlyRate" int,
  "created_at" timestamp
);

CREATE TABLE "fullTime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fulltimeID" int,
  "Salary" int,
  "created_at" timestamp
);

CREATE TABLE "leaves" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LeaveId" int,
  "leaveNum" int,
  "position" varchar,
  "created_at" timestamp
);

CREATE TABLE "Training" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trainingId" int,
  "Type" varchar,
  "number" int,
  "position" varchar,
  "created_at" timestamp
);

CREATE TABLE "Attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AttendanceId" int,
  "position" varchar,
  "Number" int,
  "Date" int,
  "created_at" timestamp
);

ALTER TABLE "departments" ADD FOREIGN KEY ("departmentId") REFERENCES "users" ("id");

ALTER TABLE "positions" ADD FOREIGN KEY ("postId") REFERENCES "departments" ("id");

ALTER TABLE "employmentType" ADD FOREIGN KEY ("TypeId") REFERENCES "positions" ("id");

ALTER TABLE "partTime" ADD FOREIGN KEY ("ParttimeID") REFERENCES "employmentType" ("id");

ALTER TABLE "fullTime" ADD FOREIGN KEY ("fulltimeID") REFERENCES "employmentType" ("id");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "leaves" ("LeaveId");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "Training" ("trainingId");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "Attendance" ("AttendanceId");
