DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullName" varchar,
  "department" integer,
  "employmentType" integer,
  "position" integer,
  "leave" integer,
  "training" integer,
  "attendance" integer,
  "created_at" timestamp
);

INSERT INTO users
(fullName, department, employmentType, position, leave, training, attendance) 
VALUES
('Mike Tyson', 'HR', 'Full-Time', 'HR Manager', 10, 'Onboarding', 'Present'),
('Lebron James', 'Marketing', 'Part-Time', 'Marketing Coordinator', 5, 'Marketing Strategy', 'Present'),
('Mike Johnson', 'IT', 'Full-Time', 'Systems Administrator', 12, 'Cybersecurity', 'Absent'),
('Sarah Brown', 'Finance', 'Full-Time', 'Financial Analyst', 8, 'Financial Planning', 'Present'),
('David Lee', 'Sales', 'Part-Time', 'Sales Associate', 7, 'Sales Techniques', 'Present');

DROP TABLE IF EXISTS departments CASCADE;
CREATE TABLE "departments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departmentId" int,
  "title" varchar,
  "description" varchar,
  "created_at" timestamp
);

INSERT INTO departments
("id", "title", "description", "created_at")
VALUES
(1, 'HR', 'Human Resources Department', '2023-09-12 10:00:00'),
(2, 'Marketing', 'Marketing Department', '2023-09-12 10:15:00'),
(3, 'IT', 'Information Technology Department', '2023-09-12 10:30:00'),
(4, 'Finance', 'Finance Department', '2023-09-12 10:45:00'),
(5, 'Sales', 'Sales Department', '2023-09-12 11:00:00');

DROP TABLE IF EXISTS positions CASCADE;
CREATE TABLE "positions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postId" int,
  "department" integer,
  "position" varchar,
  "created_at" timestamp
);

INSERT INTO positions
("id", "postId" "department", "position", "created_at")
VALUES
(1, 1, 1, 'HR Manager', '2023-09-12 13:00:00'),
(2, 2, 2, 'Marketing Coordinator', '2023-09-12 13:15:00'),
(3, 3, 3, 'Systems Administrator', '2023-09-12 13:30:00'),
(4, 4, 4, 'Financial Analyst', '2023-09-12 13:45:00'),
(5, 5, 5, 'Sales Associate', '2023-09-12 14:00:00');

DROP TABLE IF EXISTS employmentTypes CASCADE;

CREATE TABLE "employmentType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TypeId" int,
  "employment" varchar,
  "created_at" timestamp
);

INSERT INTO employmentTypes
("id", "TypeId" "employment", "created_at")
VALUES
(1, 1, 'Full-Time', '2023-09-12 15:00:00'),
(2, 2, 'Part-Time', '2023-09-12 15:15:00'),
(3, 3, 'Contract', '2023-09-12 15:30:00'),
(4, 4, 'Temporary', '2023-09-12 15:45:00');


DROP TABLE IF EXISTS partTime CASCADE;
CREATE TABLE "partTime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ParttimeID" int,
  "hourlyRate" int,
  "created_at" timestamp
);

INSERT INTO partTime
("id", "parttimeID", "salary", "attendance", "date", "created_at")
VALUES
(1, 1, 60000, 20, '2023-09-01 00:00:00', '2023-09-12 16:00:00'),
(2, 2, 40000, 18, '2023-09-01 00:00:00', '2023-09-12 16:15:00'),
(3, 3, 70000, 16, '2023-09-01 00:00:00', '2023-09-12 16:30:00'),
(4, 4, 55000, 20, '2023-09-01 00:00:00', '2023-09-12 16:45:00'),
(5, 5, 45000, 19, '2023-09-01 00:00:00', '2023-09-12 17:00:00');

DROP TABLE IF EXISTS fullTime CASCADE;
CREATE TABLE "fullTime" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fulltimeID" int,
  "Salary" int,
  "created_at" timestamp
);

INSERT INTO partTime
("id", "fulltimeID", "salary", "attendance", "date", "created_at")
VALUES
(1, 1, 60000, 20, '2023-09-01 00:00:00', '2023-09-12 16:00:00'),
(2, 2, 40000, 18, '2023-09-01 00:00:00', '2023-09-12 16:15:00'),
(3, 3, 70000, 16, '2023-09-01 00:00:00', '2023-09-12 16:30:00'),
(4, 4, 55000, 20, '2023-09-01 00:00:00', '2023-09-12 16:45:00'),
(5, 5, 45000, 19, '2023-09-01 00:00:00', '2023-09-12 17:00:00');

DROP TABLE IF EXISTS leaves CASCADE;
CREATE TABLE "leaves" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LeaveId" int,
  "leaveNum" int,
  "position" varchar,
  "created_at" timestamp
);

INSERT INTO leaves
("id", "trainingId", "type", "position", "created_at")
VALUES
(1, 1, 1, 1, '2023-09-12 17:00:00'),
(2, 2, 2, 2, '2023-09-12 17:15:00'),
(3, 3, 3, 3, '2023-09-12 17:30:00'),
(4, 4, 4, 4, '2023-09-12 17:45:00'),
(5, 5, 5, 5, '2023-09-12 18:00:00'


CREATE TABLE "Training" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trainingId" int,
  "Type" int,
  "number" int,
  "position" int,
  "created_at" timestamp
);

INSERT INTO Trainings
("id", "trainingId", "type", "number" "position", "created_at")
VALUES
(1, 1, 1, 1, 1, '2023-09-12 18:00:00'),
(2, 2, 2, 2, 2, '2023-09-12 18:15:00'),
(3, 3, 3, 3, 3, '2023-09-12 18:30:00'),
(4, 4, 4, 4, 4, '2023-09-12 18:45:00'),
(5, 5, 5, 5, 5, '2023-09-12 19:00:00');

DROP TABLE IF EXISTS Attendance CASCADE;
CREATE TABLE "Attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AttendanceId" int,
  "position" varchar,
  "Number" int,
  "Date" int,
  "created_at" timestamp
);

INSERT INTO attendances
("id", "AttendanceId", "position", "number", "Date", "created_at")
VALUES
(1, 1, 1, 1, '2023-09-01 09:00:00', '2023-09-12 19:00:00'),
(2, 2, 2, 2, '2023-09-01 09:15:00', '2023-09-12 19:15:00'),
(3, 3, 3, 3, '2023-09-01 09:30:00', '2023-09-12 19:30:00'),
(4, 4, 4, 4, '2023-09-01 09:45:00', '2023-09-12 19:45:00'),
(5, 5, 5, 5, '2023-09-01 10:00:00', '2023-09-12 20:00:00');

ALTER TABLE "departments" ADD FOREIGN KEY ("departmentId") REFERENCES "users" ("id");

ALTER TABLE "positions" ADD FOREIGN KEY ("postId") REFERENCES "departments" ("id");

ALTER TABLE "employmentType" ADD FOREIGN KEY ("TypeId") REFERENCES "positions" ("id");

ALTER TABLE "partTime" ADD FOREIGN KEY ("ParttimeID") REFERENCES "employmentType" ("id");

ALTER TABLE "fullTime" ADD FOREIGN KEY ("fulltimeID") REFERENCES "employmentType" ("id");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "leaves" ("LeaveId");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "Training" ("trainingId");

ALTER TABLE "departments" ADD FOREIGN KEY ("id") REFERENCES "Attendance" ("AttendanceId");
